#!/bin/bash
# sudo-wrapper pour exécuter cranspasswords côté serveur
# Beware : code potentiellement mort (clientconfig fait un appel immédiat à sudo)
# -- DS 01/08/2013

cmd_name=cranspasswords
sudo -n /usr/local/bin/${cmd_name}/server.py "$@"
